/* ============================================================
   LOOT ITEM CATALOG — canonical D&D 5e items (SRD 5.1 / PHB / DMG),
   for quick-adding to the Tracker's loot list. One object per item;
   duplicate an entry to add more.
   ============================================================ */
const LOOT_ITEMS = [
  { id:"potion-of-healing", name:"Potion of Healing", category:"Potion", rarity:"Common",
    description:"A creature that drinks this red, bubbling liquid regains 2d4 + 2 hit points." },
  { id:"potion-of-greater-healing", name:"Potion of Greater Healing", category:"Potion", rarity:"Uncommon",
    description:"Drinking this potion restores 4d4 + 4 hit points." },
  { id:"potion-of-climbing", name:"Potion of Climbing", category:"Potion", rarity:"Common",
    description:"For 1 hour, the drinker gains a climbing speed equal to their walking speed and advantage on Strength (Athletics) checks to climb." },
  { id:"potion-of-animal-friendship", name:"Potion of Animal Friendship", category:"Potion", rarity:"Uncommon",
    description:"Lets the drinker cast animal friendship (DC 13) on themselves once within the next hour." },
  { id:"potion-of-fire-breath", name:"Potion of Fire Breath", category:"Potion", rarity:"Uncommon",
    description:"As an action, the drinker can exhale fire in a 30-foot line for 4d6 fire damage (DC 13 Dex save for half); usable once." },
  { id:"potion-of-water-breathing", name:"Potion of Water Breathing", category:"Potion", rarity:"Uncommon",
    description:"The drinker can breathe underwater for 1 hour." },
  { id:"potion-of-resistance", name:"Potion of Resistance", category:"Potion", rarity:"Uncommon",
    description:"Grants resistance to one damage type (set when brewed) for 1 hour." },
  { id:"potion-of-growth", name:"Potion of Growth", category:"Potion", rarity:"Uncommon",
    description:"Functions as the enlarge/reduce spell (enlarge only) on the drinker for 1d4 hours." },
  { id:"potion-of-invisibility", name:"Potion of Invisibility", category:"Potion", rarity:"Very Rare",
    description:"The drinker becomes invisible for 1 hour, or until they attack or cast a spell." },

  { id:"scroll-cure-wounds", name:"Spell Scroll: Cure Wounds", category:"Scroll", rarity:"Common",
    description:"A one-use scroll that casts cure wounds at 1st level for whoever reads it." },
  { id:"scroll-identify", name:"Spell Scroll: Identify", category:"Scroll", rarity:"Common",
    description:"A one-use scroll that casts identify." },
  { id:"scroll-magic-missile", name:"Spell Scroll: Magic Missile", category:"Scroll", rarity:"Common",
    description:"A one-use scroll that casts magic missile at 1st level." },
  { id:"scroll-protection-evil-good", name:"Spell Scroll: Protection from Evil and Good", category:"Scroll", rarity:"Uncommon",
    description:"A one-use scroll that casts protection from evil and good." },
  { id:"scroll-fireball", name:"Spell Scroll: Fireball", category:"Scroll", rarity:"Uncommon",
    description:"A one-use scroll that casts fireball at 3rd level." },

  { id:"bag-of-holding", name:"Bag of Holding", category:"Wondrous Item", rarity:"Uncommon",
    description:"Opens into a 500 lb./64 cu. ft. extradimensional space, weighing only 15 lb. no matter what's inside." },
  { id:"bag-of-tricks", name:"Bag of Tricks", category:"Wondrous Item", rarity:"Uncommon",
    description:"Reach in and pull out a stuffed, fuzzy object that becomes a random small animal fighting on your behalf, once per day." },
  { id:"cloak-of-elvenkind", name:"Cloak of Elvenkind", category:"Wondrous Item", rarity:"Uncommon",
    description:"While the hood is up, advantage on Stealth checks and disadvantage on Perception checks made to see the wearer." },
  { id:"cloak-of-protection", name:"Cloak of Protection", category:"Wondrous Item", rarity:"Uncommon",
    description:"+1 bonus to AC and saving throws while worn." },
  { id:"boots-of-elvenkind", name:"Boots of Elvenkind", category:"Wondrous Item", rarity:"Uncommon",
    description:"The wearer's steps make no sound, and they have advantage on Dexterity (Stealth) checks that rely on moving silently." },
  { id:"boots-of-striding-and-springing", name:"Boots of Striding and Springing", category:"Wondrous Item", rarity:"Uncommon",
    description:"Walking speed becomes 30 ft. unless already higher; long/high jump distance triples." },
  { id:"gloves-of-thievery", name:"Gloves of Thievery", category:"Wondrous Item", rarity:"Uncommon",
    description:"+5 bonus to Sleight of Hand checks and Dexterity checks made to pick locks with thieves' tools." },
  { id:"bracers-of-archery", name:"Bracers of Archery", category:"Wondrous Item", rarity:"Uncommon",
    description:"Grants proficiency with the longbow and shortbow, plus +2 to damage rolls made with either." },
  { id:"driftglobe", name:"Driftglobe", category:"Wondrous Item", rarity:"Uncommon",
    description:"A floating glass sphere that sheds light and can be commanded to hover, glow, or cast daylight or faerie fire once per day." },
  { id:"alchemy-jug", name:"Alchemy Jug", category:"Wondrous Item", rarity:"Uncommon",
    description:"Once per day, produce up to 2 gallons of a chosen mundane liquid — vinegar, oil, acid, and more." },
  { id:"immovable-rod", name:"Immovable Rod", category:"Wondrous Item", rarity:"Uncommon",
    description:"Press the button and the rod stays fixed in place, holding up to 8,000 lb., until pressed again." },
  { id:"sending-stones", name:"Sending Stones", category:"Wondrous Item", rarity:"Uncommon",
    description:"A pair of stones lets holders send a short telepathic message to each other once per day." },

  { id:"wand-of-magic-missiles", name:"Wand of Magic Missiles", category:"Wand", rarity:"Uncommon",
    description:"Cast magic missile from this wand (7 charges, up to 5th level); regains 1d6 + 1 expended charges daily." },
  { id:"wand-of-secrets", name:"Wand of Secrets", category:"Wand", rarity:"Uncommon",
    description:"Points toward the nearest secret door or trap within 30 feet; 3 charges, regains 1d3 daily." },

  { id:"ring-of-warmth", name:"Ring of Warmth", category:"Ring", rarity:"Uncommon",
    description:"Resistance to cold damage, and comfortable in temperatures as low as -50°F while worn." },
  { id:"ring-of-protection", name:"Ring of Protection", category:"Ring", rarity:"Rare",
    description:"+1 bonus to AC and saving throws while worn." }
];
